name: Validate Terraform
on:
  push:
  pull_request:
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: terraform-validate
      uses: dflook/terraform-validate@v1.29.1
      env:
        TERRAFORM_PRE_RUN: |
          rm *.tfstate  
    - name: Validate failed
      if: ${{ failure() && steps.validate.outputs.failure-reason == 'validate-failed' }}
      run: echo "terraform validate failed"
